# Generated by Django 4.0.3 on 2022-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_botuser_full_name_botuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='title_verbose_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
