# Generated by Django 4.0.3 on 2022-03-19 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_botuser_bot_state_botuser_created_botuser_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewvideo',
            name='created',
        ),
        migrations.AddField(
            model_name='viewvideo',
            name='sended',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Отправлено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм'),
        ),
    ]
