# Generated by Django 4.0.3 on 2022-03-19 10:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_viewvideo_created_viewvideo_sended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
