# Generated by Django 4.0.3 on 2022-03-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_viewvideo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewvideo',
            old_name='viewed',
            new_name='received',
        ),
    ]
