# Generated by Django 4.0.3 on 2022-03-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_botuser_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='referals',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals', to='backend.botuser', verbose_name='Кто пригласил'),
        ),
    ]
