# Generated by Django 4.0.3 on 2022-03-25 11:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_botuser_referals_alter_botuser_invited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка(опционально)')),
                ('start_date', models.DateField(verbose_name='Дата первой отправки')),
                ('period', models.CharField(choices=[('O', 'Одиножды'), ('D', 'Ежедневный'), ('H', 'Ежечасный')], max_length=1)),
                ('repeats', models.IntegerField(default=1, verbose_name='Количество повторов')),
            ],
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
