# Generated by Django 4.0.3 on 2022-03-25 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('backend', '0014_alter_post_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.schedule'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка(опционально)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.CharField(choices=[('H', 'Ежечасный'), ('D', 'Ежедневный')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='repeats',
            field=models.IntegerField(default=1, verbose_name='Количество повторов(-1 для бесконечного повтора)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата первой отправки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название(для себя)'),
        ),
    ]
