# Generated by Django 4.0.3 on 2022-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_post_schedule_alter_post_image_alter_post_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backend/posts', verbose_name='Картинка(опционально)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.CharField(choices=[('H', 'Ежечасный'), ('D', 'Ежедневный')], max_length=1, verbose_name='Период'),
        ),
    ]
